### ISSUE TITLE
UserDefined() may not be everyehere where it should be

### ISSUE THREAD

**Issue by xsmrcek** [EmbedITCZ/jbehave-support#191]
Not all values saved to context by user, can be seen in report.

**Comment by xsmrcek** [comment]
Following part of code is responsible for that:
`    public static void putDataIntoContext(final TestContext testContext, final ExamplesTable data, final String prefix) {
        List<Parameters> rows = data.getRowsAsParameters();
        rows.forEach(row -> {
            String name = row.valueAs(ExampleTableConstraints.NAME, String.class);
            String key = (!Strings.isNullOrEmpty(prefix)) ? String.join(CONTEXT_DELIMITER, prefix, name) : name;
            String value = row.valueAs(ExampleTableConstraints.DATA, String.class);
            String type = row.values().containsKey(ExampleTableConstraints.TYPE) ? row.valueAs(ExampleTableConstraints.TYPE, String.class) : null;

            if (isNoneEmpty(type)) {
                testContext.put(key, null, MetadataUtil.type(type));
            } else {
                testContext.put(key, value);
            }

            if (data.getHeaders().contains(ExampleTableConstraints.ALIAS)) {
                String alias = row.valueAs(ExampleTableConstraints.ALIAS, String.class);
                if (!alias.isEmpty()) {
                    testContext.put(alias, value, MetadataUtil.userDefined());
                }
            }
        });
    }`

We should think about rewriting this step to always add UserDefined() metadata, as this behaviour is not mentioned in MDs and users are complaining about missing records in text context report extension.

**Comment by xsmrcek** [comment]
Sorry for bad formating of code, It is not cooperating with mne :D

**Comment by xsmrcek** [comment]
I did my homework about contextAlias/data column:
SQLSteps:
`When these columns from the single-row query result are saved:
| name          | contextAlias     |
| FIRST_NAME     | FIRST_NAME       |
| LAST_NAME      | LAST_NAME        |
| IS_BLOCKED     | BLOCKED          |
| IS_DEACTIVATED | DEACTIVATED      |`
`When these columns from the multi-row query result are saved:
| name           | contextAlias     |
| FIRST_NAME     | FIRST_NAME       |
| LAST_NAME      | LAST_NAME        |
| IS_BLOCKED     | BLOCKED          |
| IS_DEACTIVATED | DEACTIVATED      |`
RestSteps:
`When response values from [TEST] REST API are saved:
| name                      | contextAlias      |
| @header.Transfer-Encoding | TRANSFER_ENCODING |`
`When [POST] request to [TEST]/[user/] is sent with data:
| name      | data               | contextAlias |
| firstName | Bruno              |              |
| lastName  | {RANDOM_STRING:10} | LAST_NAME    |`
WebServiceSteps:
`Given [ClientRequest] data for [MYAPP]:
| name               | data               | contextAlias    |
| client.firstName   | {RANDOM_STRING:10} | FIRST_NAME_1    |
| client.lastName    | {RANDOM_STRING:15} | LAST_NAME_1     |
| client.dateOfBirth | {RANDOM_DATE}      | DATE_OF_BIRTH_1 |`
`Given [ClientRequest] values from [MYAPP] are saved:
| name      | contextAlias |
| client.id | ID           |`
WebSteps:
`Then on [home] page these values are saved:
| element    | property | contextAlias   |
| client.id  | VALUE    | ID             |
| client.ssn | VALUE    | SSN            |`

And now testContext:
`Given the following values are saved:
| name                  | data               |
| FIRST_NAME            | {RANDOM_STRING:10} |
| LAST_NAME             | {RANDOM_STRING:15} |`
`Given the following test constants with prefix CONSTANTS and values:
| name                  | data               |
| FIRST_NAME            | {RANDOM_STRING:10} |
| LAST_NAME             | {RANDOM_STRING:15} |`

So in my opinion TestContextSteps are wrong.
can we please talk about it again? I don't care what columns will be used in future, but we should use only one solution. Maybe major release after this? :D

**Comment by xsmrcek** [comment]
> Given the following test constants with prefix CONSTANTS and values:
> | name | data |
> | FIRST_NAME | {RANDOM_STRING:10} |
> | LAST_NAME | {RANDOM_STRING:15} |

-doesn't even exist.

And 
> Given the following values are saved:

- doesn't support name and contextAlias columns (only two) as all another steps do!!!

**Comment by xsmrcek** [comment]
Agreed fix:

Given the following values are saved:
| name | data |
| FIRST_NAME | {RANDOM_STRING:10} |
| LAST_NAME | {RANDOM_STRING:15} |

Step should keep same columns but add UserDefined flag to saved data.

**Comment by paveljandejsek** [comment]
Solved by #238
