### ISSUE TITLE
Add CURRENT/RANDOM/FORMAT_DATE_TIME commands

### ISSUE THREAD

**Issue by thradec** [EmbedITCZ/jbehave-support#28]
currently we have support only for CURRENT_DATE

**Comment by thradec** [comment]
well, our use case was for date+time, if somebody needs only time, I think we could add it, but that is for different issue

**Comment by paveljandejsek** [comment]
Ok, in that case I would probably consider adding to this issue something like FORMAT_DATE_TIME + maybe RANDOM_DATE_TIME commands to keep some functionality parity between date/dateTime
