### ISSUE TITLE
TestContext not displayed in report (1.1.0 jbehave-support)

### ISSUE THREAD

**Issue by TheRacku** [EmbedITCZ/jbehave-support#284]
After a fresh install, running any test creates a report without the TestCOntext being displayed. The TestContext exists in the report but is not picked up by the reports.xslt template.
[reports.zip](https://github.com/EmbedITCZ/jbehave-support/files/4147199/reports.zip)

**Comment by xsmrcek** [comment]
@TheRacku Hello this issue is on forked jbus or in your own project which use jbus?

**Comment by TheRacku** [comment]
> @TheRacku Hello this issue is on forked jbus or in your own project which use jbus?

In my own project that uses jbus

**Comment by xsmrcek** [comment]
Probably a stupid question.
But do you have this bean registered?
`    @Bean
    public TestContextXmlReporterExtension testContextXmlReporterExtension() {
        return new TestContextXmlReporterExtension(testContext);
    }`

**Comment by xsmrcek** [comment]
> > @TheRacku Hello this issue is on forked jbus or in your own project which use jbus?
> 
> In my own project that uses jbus

Probably a stupid question.
But do you have this bean registered?
>    @Bean
>   public TestContextXmlReporterExtension testContextXmlReporterExtension() {
>      return new TestContextXmlReporterExtension(testContext);
>  }
I just tried it on our project which uses jbus and it works as expected with this bean.

**Comment by TheRacku** [comment]
> > > @TheRacku Hello this issue is on forked jbus or in your own project which use jbus?
> > 
> > 
> > In my own project that uses jbus
> 
> Probably a stupid question.
> But do you have this bean registered?
> 
> > @bean
> > public TestContextXmlReporterExtension testContextXmlReporterExtension() {
> > return new TestContextXmlReporterExtension(testContext);
> > }
> > I just tried it on our project which uses jbus and it works as expected with this bean.

I have yes. 
This is a new project where I used this, basically a clean install and I just @Autowired the testContext and the rest required.

**Comment by TheRacku** [comment]
After a closer investigation, when I ported the pom file to another project, I left some dependencies of the old report.xslt. 
Removing them solved the problem, my bad.
Credits to Pavel J.
