### ISSUE TITLE
Firing wrong JavaScript event

### ISSUE THREAD

**Issue by riskaverse** [EmbedITCZ/jbehave-support#331]
When using libraries like react which uses **virtual dom** to compare and render particular html only when state changes, sometimes could be tricky to JBehave. Few days ago I had been working with a react based project where i should test delete functionality of particular item. Where the delete button is a part of drop down list ("ul->li->a(javascript onclick event)") which exists in the end of drop down list and the JavaScript event been attached to it within "onClick" event handler. So, every time when i was running tests with JBehave it fired wrong event, the event of another button in that drop down list(Cancel Goal button) which was one level up and in the same drop down list, i added data-test selectors to html in order to be sure that it clicks correct button but the result was the same it clicked correct button but fired wrong event. After that i added 2 seconds timeout method to my .story file and then it worked as expected.

**NOTE: If the desired button in our example is on very top of drop down list then it fires correct event**

**Comment by paveljandejsek** [comment]
Will be added to doc to some section like _known issues_
