### ISSUE TITLE
Allow to save query result with prefix

### ISSUE THREAD

**Issue by MartinParenica** [EmbedITCZ/jbehave-support#382]
- it would be good to have an option to save query values directly with some defined prefix in case there will be multiple sets of data with the same aliases
- so to modify this step:

When these columns from the single-row query result are saved:
| name | contextAlias |

- somehow like:

When these columns from the single-row query result are saved with prefix [SET_1]:
| name | contextAlias |

**Comment by xsmrcek** [comment]
Won't implement.
