### ISSUE TITLE
Support for Splunk logs verification

### ISSUE THREAD

**Issue by stjarna** [EmbedITCZ/jbehave-support#398]
Given that new apps get deployed to Kubernetes cluster and SSH custom step is not applicable in such case, JBUS could support custom steps related to log verification in Splunk.

It would be similar to what is already available in [SSH](https://github.com/EmbedITCZ/jbehave-support/blob/master/jbehave-support-core/docs/Ssh.md).

Instead of ssh hostnames, it would support Splunk hostname, custom index name/search expression.
Though not sure about APITokens or some kind of credentials that will let to call Splunk with technical account.

**Comment by paveljandejsek** [comment]
Solved by #411 and #521
