### ISSUE TITLE
Investigate source mismatch in IDEs

### ISSUE THREAD

**Issue by paveljandejsek** [EmbedITCZ/jbehave-support#516]
Might be caused by:
https://stackoverflow.com/questions/36753524/library-source-does-not-match-the-bytecode-for-class

We should check the difference and see if its caused by lombok or something else.

**Comment by paveljandejsek** [comment]
Looks like an issue with lombok:
![image](https://user-images.githubusercontent.com/43804753/105609645-f7507200-5daa-11eb-908b-983a89901134.png)

And exactly this one mentioned here: https://github.com/mplushnikov/lombok-intellij-plugin/issues/438
Do we want to delombok in the pipeline before publishing sources? @EmbedITCZ/jbehave-support-dev what do the rest of you think?

**Comment by paveljandejsek** [comment]
Closing for now, seems more like an issue between lombok and IDE support, so hopefully it will get solved at some point (without us having to delombok and unnecessarily complicate our pipeline)

**Comment by isdeniz** [comment]
Hi, I am not a user of the repository but just wondering why this issue is labeled as an enhancement. Would not it be more appropriate labeling it as a bug since it is pointing to a mismatch situation? Asking just to understand the rationale behind issue labels. Thanks in advance!

**Comment by paveljandejsek** [comment]
Hi @isdeniz, maybe, but while there is a warning being issued the sources published are still the "correct" ones, so from our POV its not a bug on our side (maybe a bug in IDE support or lombok) and solving this is not a priority for us (but really just a nice to have enhancement that changes nothing in the functionality of the library).

Hope it makes sense
