### ISSUE TITLE
RestSteps don't send GET with header

### ISSUE THREAD

**Issue by tommyk85** [EmbedITCZ/jbehave-support#549]
When [GET] request to [LRP]/[accounts/{CP:CONTRACT_CODE}] is sent with data:
| name           | data      |
| @header.x-cuid | {CP:CUID} |

then the header is not included in the request

**Comment by paveljandejsek** [comment]
Can you post some more details please? I have been able to get this working...

Client side sending the request from story:
![image](https://user-images.githubusercontent.com/43804753/104629342-aac5b200-5699-11eb-857e-39ba787b5d70.png)

Server side receiving request:
![image](https://user-images.githubusercontent.com/43804753/104629615-02641d80-569a-11eb-8fec-733b34b14645.png)

**Comment by paveljandejsek** [comment]
Solved during a call, works correctly in the end 🙂
