### ISSUE TITLE
Number formatting issue

### ISSUE THREAD

**Issue by xsmrcek** [EmbedITCZ/jbehave-support#661]
It may happend that we save number in scientific format to context. We need a way out of it. <br>
I would propose command to reformat string representation of number  ('1.0E7' to '10000000') <br> 
and NUMERIC_EQUALS verifier which would convert anything to bigDecimals and then compare it (string like 1.0E7, 10000000, 10000000.00 are not equal but numbers are).

Demonstare issue with saving to context:
```json
[
    {
        "code": "29821207",
        "type": "Two weelers",
        "category": "Two weelers",
        "producerCode": "HONDA",
        "producerText": null,
        "serialNumber": "391947",
        "modelNumber": null,
        "engineNumber": null,
        "licencePlateNumber": null,
        "price": 25000000,
        "imei": null
    },
    {
        "code": "29821208",
        "type": "Other Two Wheelers",
        "category": "Two weelers",
        "producerCode": "YAMAHA",
        "producerText": null,
        "serialNumber": "14006991",
        "modelNumber": null,
        "engineNumber": null,
        "licencePlateNumber": null,
        "price": 10000000,
        "imei": null
    }
]
```

>Then response values from [TEST] REST API are saved: 
>| name           | contextAlias |
>| $.[0].price    | TEST_VALUE   |

produce: '25000000'

```json
{
    "contracts": [
        {
            "contractNumber": "4100903790",
            "type": "CEL",
            "contractStatusCode": "A",
            "loanAmount": {
                "currency": "VND",
                "value": 17587635
          },
            "instalmentAmount": {
                "currency": "VND",
                "value": 810000
            },
            "signatureDate": "2021-05-18",
            "lastInstalmentDate": "2024-05-18",
            "term": 36,
            "interestRate": 0.354862,
            "productCode": "TW17AD",
            "productBusinessDescription": "TW ULTIMATE DL",
            "processingFee": null,
            "safePayFee": null,
            "initTransactionType": "POS",
          "commodities": [
                {
                    "code": "29821207",
                    "type": "Two weelers",
                    "category": "Two weelers",
                    "producerCode": "HONDA",
                    "producerText": null,
                    "serialNumber": "391947",
                    "modelNumber": null,
                    "engineNumber": null,
                    "licencePlateNumber": null,
                    "price": 25000000,
                    "imei": null
                },
                {
                    "code": "29821208",
                    "type": "Other Two Wheelers",
                    "category": "Two weelers",
                    "producerCode": "YAMAHA",
                    "producerText": null,
                    "serialNumber": "14006991",
                    "modelNumber": null,
                    "engineNumber": null,
                    "licencePlateNumber": null,
                    "price": 10000000,
                    "imei": null
                }
            ],
            "commoditiesCallResult": "SUCCESS"
        }
    ]
}
```

>Then response values from [TEST] REST API are saved:
>| name                                | contextAlias |
>| $.contracts[0].commodities[0].price | TEST_VALUE   |

produce '2.5E7'

**Comment by romcooo** [comment]
@xsmrcek is it necessary or preferrable to have a separate verifier for mathematical equality? EQ could simply accept math equality as well, do you think it'd be better to keep them separate?

**Comment by xsmrcek** [comment]
@romcooo it's nice to hear from you again :)
Using EQ for that have one issue: What if someone for some reason wants to check that two strings (both numeric) are equals, but one of them is '2.5E7' and second one is '25000000', those numbers are equal but string aren't :)

**Comment by romcooo** [comment]
@xsmrcek 
I had a moment of nostalgia and some free time and decided to check this repo to see if there was someting for me to potentially do :).

I see, I had thought of that as well, it just seemed like a very unlikely scenario, and adding another verifier command might be slightly confusing to people writing the tests, which is why I thought it could be better to leave it under one.
However, you're right that it could cause an issue.
How about MATH_EQ?

**Comment by xsmrcek** [comment]
@romcooo there is always plenty of stuf to do :)
