### ISSUE TITLE
WebServiceHandler should not use String based comparison

### ISSUE THREAD

**Issue by paveljandejsek** [EmbedITCZ/jbehave-support#81]
Currently the code of web service handler uses the following:
```
String expectedValue = p.valueAs(ExampleTableConstraints.EXPECTED_VALUE, String.class);
Object actualValue = ReflectionUtils.getPropertyValue(bean, propertyName);
getVerifier(p).verify(actualValue, expectedValue);
```

This works for types that have a toString conversion that is comparable, but not for those that dont, e.g `byte[]` (toString something like `[B@c4f5e6]`) that is used when `xs:base64binary` is used.

IMO we should change the expectedValue to use Object if possible

**Comment by Hebcak** [comment]
`expectedValue` has to be a String as the value is pulled from a String map, to which it is stored as a String the user writes into a story. `actualValue` can be anything.
If we wanted to make sure nothing String-uncomperable is in `actualValue`, we would have to do some tedious primitive type comparison magic.
