### ISSUE TITLE
Add option to make screenshots

### ISSUE THREAD

**Issue by paveljandejsek** [EmbedITCZ/jbehave-support#86]
We should consider adding option for the user to make screenshots and to make these screenshots visible in the report. (right now we only support error screenshots)

There could be several ways to go with this which might possibly be driven by some setting, e.g. make screen after every step, make screen after every webdriver action, manual screenshot option.

**Comment by xsmrcek** [comment]
Basic code done.
New step is implementing some kind of listener.

**Comment by xsmrcek** [comment]
Solved by #181 #157 #138
