### ISSUE TITLE
Random date in range

### ISSUE THREAD

**Issue by AmyKosinova** [EmbedITCZ/jbehave-support#93]
Random date command should support optional parameters as range in which the date should be created.

**Comment by paveljandejsek** [comment]
We should probably add this to datetime variant as well. Got a suggestion about how the usage would work? (how exactly would the range be written from user perspective?)

Btw. why the "bug" label? I dont consider it bug since we havent declared support for this so far, or have we?

**Comment by AmyKosinova** [comment]
+DateTime.
I see usages: `{RANDOM_DATE}`, `{RANDOM_DATE:<FROM>}`, `{RANDOM_DATE:<FROM>:<TO>}` Maybe some clever parser could be in behind, that handles each of: `2001`, `7.1999`, `6.1.1988` as input parameters, or let user define "project date format" which we can parse against.
![image](https://user-images.githubusercontent.com/19281259/55485291-769b1180-562a-11e9-9bb1-5067c4622f60.png)
